# Environment Configuration
dev:
  server:
    host: "localhost"
    port: "8080"
  database:
    host: "localhost"
    user: "admin"
    pass: ""
    port: "27017"
    dbname: "sample"
qa:
  server:
    host: "localhost"
    port: "9090"
  database:
    host: "localhost"
    user: "admin"
    pass: ""
    port: "27017"
    dbname: "sample"
stg:
  server:
    host: "localhost"
    port: "8888"
  database:
    host: "localhost"
    user: "admin"
    pass: ""
    port: "27017"
    dbname: "sample"
prod:
  server:
    host: "localhost"
    port: "9999"
  database:
    host: "localhost"
    user: "admin"
    pass: ""
    port: "27017"
    dbname: "sample"